[project]
name = "grpo-rl-trainer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.0",
    "torch>=2.6.0",
]

[dependency-groups]
dev = [
    "gym>=0.26.2",
]
